POST http://localhost:5722/api/notes/create-note HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZlbGlwZSIsInVzZXJpZCI6IjV1ODksNHxsNDJuWDhfQjU0MDF7V2hPMsK6fV9JLDQyckQ2Jy00eDMvIiwiZW1haWwiOiJtYXNpY3dhZGF3ZEBnbWFpbC5jb20iLCJpYXQiOjE2ODkxNTI5OTJ9.UZjflg2uqCnWzqMMBs4-Tr9f3R0mtf3YDI2Llm4Gf8E

{
  "title": "53",
  "priority": 1,
  "text": "¿Capitalismo o socialismo? El papel lo aguanta todo, pero los datos ponen de manifiesto la enorme brecha existente entre los resultados socioeconómicos que arrojan ambos sistemas. Así lo pone de manifiesto la última edición del Índice de Libertad Económica, que elabora la Fundación Heritage y difunde en España el Instituto de Estudios Económicos."
}