POST http://localhost:5722/api/notes/create-note HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9zdmkiLCJ1c2VyaWQiOiJnOHlyNHZFMntGfUzCujRxNXI4MjkiLCJlbWFpbCI6bnVsbCwiaWF0IjoxNjg3NzI3MjMxfQ.BLUPNOxp94VOpQDoSMbaVLHqF0zMVn9PNP9LhtpV-HY

{
  "title": "Pollo2",
  "priority": 5,
  "text": "Madre mia pollo2"
}